name: pipes
version: 0.0.2
author: Alexander Adeniyin Ewetumo <trinoxf@gmail.com>
repository: http://github.com/influx/stream.dart
homepage: http://influx.github.com/stream.dart
description: a library of helpful custom stream candies
dependencies:
  hub: any
  ds: any
