name: pipes
version: 0.0.4
author: Alexander Adeniyin Ewetumo <trinoxf@gmail.com>
homepage: http://influx.github.com/pipes.dart
description: a library of helpful custom stream candies
dependencies:
  hub: any
  ds: any
